### ISSUE TITLE
It doesn't work with ionic 'ready-made' tabs template

### ISSUE THREAD

**Issue by aironpower** [ngx-translate/ionic-example#1]
This is a very good job, congratulations!
I'm trying to use it in a project that uses tabs but the translator is not working at home page.
You can see my code [here ](https://forum.ionicframework.com/t/ngx-translate-not-wotking-with-ready-made-tabs-template/129984?u=aironpower)

Do you have any idea?
Thank you in advance!

**Comment by ansarikhurshid786** [comment]
versioning issue right? if yes close this issue.
